const statusEl=document.querySelector('#admin-status'),pendingEl=document.querySelector('#pending-list'),publishedEl=document.querySelector('#published-list'),contactEl=document.querySelector('#contact-requests-list');
const escapeHTML=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const headers=()=>({Authorization:`Bearer ${document.querySelector('#admin-token').value}`});
async function fetchList(status){const r=await fetch(`/api/admin/guests?status=${status}`,{headers:headers()});if(!r.ok)throw new Error(r.status===401?'令牌无效。':'暂时无法加载资料。');return r.json();}
async function fetchContactRequests(status){const r=await fetch(`/api/admin/contact-requests?status=${status}`,{headers:headers()});if(!r.ok)throw new Error(r.status===401?'令牌无效。':'暂时无法加载联系申请。');return r.json();}
function card(g,mode){const actions=mode==='pending'?`<button class="button primary" data-type="guest" data-id="${g.id}" data-status="published">发布</button> <button class="button ghost" data-type="guest" data-id="${g.id}" data-status="rejected">拒绝</button>`:`<button class="button ghost" data-type="guest" data-id="${g.id}" data-status="rejected">下架</button>`;return `<article class="card">${g.photo_key?`<img class="photo" src="/api/photos/${encodeURIComponent(g.photo_key)}" alt="照片">`:''}<div class="card-body"><h3>${escapeHTML(g.name)} · ${g.age}岁</h3><p class="meta">${escapeHTML(g.gender)}士 · ${escapeHTML(g.city)}</p><p class="bio">${escapeHTML(g.bio)}</p>${actions}</div></article>`}
function contactCard(cr){return `<article class="card"><div class="card-body"><h3>想联系：${escapeHTML(cr.guest_name)}</h3><p class="meta">嘉宾联系方式：${escapeHTML(cr.guest_contact||'（未填写）')}</p><p class="meta">申请人联系方式：${escapeHTML(cr.requester_contact)}</p>${cr.message?`<p class="bio">留言：${escapeHTML(cr.message)}</p>`:''}<button class="button primary" data-type="contact" data-id="${cr.id}" data-status="approved">已征得同意并转达</button> <button class="button ghost" data-type="contact" data-id="${cr.id}" data-status="declined">拒绝/不予转达</button></div></article>`}
async function load(){statusEl.textContent='正在加载…';pendingEl.innerHTML='';publishedEl.innerHTML='';contactEl.innerHTML='';try{const [pending,published,contactRequests]=await Promise.all([fetchList('pending'),fetchList('published'),fetchContactRequests('pending')]);statusEl.textContent=`待审核 ${pending.length} 条，已发布 ${published.length} 条，联系申请待处理 ${contactRequests.length} 条。`;pendingEl.innerHTML=pending.map(g=>card(g,'pending')).join('');publishedEl.innerHTML=published.map(g=>card(g,'published')).join('');contactEl.innerHTML=contactRequests.map(contactCard).join('')}catch(e){statusEl.textContent=e.message}}
document.querySelector('#load').onclick=load;
document.querySelector('main').addEventListener('click', async e=>{const b=e.target.closest('button[data-id]');if(!b)return;const path=b.dataset.type==='contact'?`/api/admin/contact-requests/${b.dataset.id}`:`/api/admin/guests/${b.dataset.id}`;try{const r=await fetch(path,{method:'PATCH',headers:{...headers(),'Content-Type':'application/json'},body:JSON.stringify({status:b.dataset.status})});if(!r.ok)throw new Error('操作未完成，请检查令牌。');await load()}catch(err){statusEl.textContent=err.message}});
