const examples=[{id:'rose',name:'若岚',gender:'女',age:28,city:'郑州',bio:'喜欢读书、散步和家常的烟火气，希望遇见愿意一起成长的人。'},{id:'sun',name:'知远',gender:'男',age:32,city:'周口',bio:'工作认真，生活简单。周末爱骑行，也想有人一起分享日落。'},{id:'leaf',name:'安然',gender:'女',age:30,city:'开封',bio:'相信舒适的关系是彼此尊重，也保留各自的热爱。'}];
const fallback=name=>`data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="600" height="500"><rect width="100%" height="100%" fill="#f5dfda"/><text x="50%" y="48%" dominant-baseline="middle" text-anchor="middle" font-size="105" fill="#b85b6e">♡</text><text x="50%" y="68%" dominant-baseline="middle" text-anchor="middle" font-size="24" fill="#8d5b65">${name}</text></svg>`)}`;
let guests=[...examples],active='all';
const list=document.querySelector('#guest-list'),empty=document.querySelector('#empty-state'),dialog=document.querySelector('#profile-dialog');
const escapeHTML=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
function photoUrl(g){return g.photo?g.photo:g.photo_key?`/api/photos/${encodeURIComponent(g.photo_key)}`:fallback(g.name)}
function render(){const shown=guests.filter(g=>active==='all'||g.gender===active);list.innerHTML=shown.map(g=>`<article class="card" data-id="${g.id}"><img class="photo" src="${photoUrl(g)}" alt="${escapeHTML(g.name)}的展示照片"><div class="card-body"><h3>${escapeHTML(g.name)} <span class="meta">· ${g.age}岁</span></h3><div class="meta">${escapeHTML(g.gender)}士 · ${escapeHTML(g.city)}</div><p class="bio">${escapeHTML(g.bio)}</p></div></article>`).join('');empty.hidden=shown.length>0}
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{active=b.dataset.filter;document.querySelector('.filter.active').classList.remove('active');b.classList.add('active');render()});
list.onclick=e=>{const card=e.target.closest('.card');if(!card)return;const g=guests.find(x=>x.id===card.dataset.id);document.querySelector('#dialog-content').innerHTML=`<img class="dialog-image" src="${photoUrl(g)}" alt="${escapeHTML(g.name)}的展示照片"><div class="dialog-body"><p class="eyebrow">嘉宾资料</p><h2>${escapeHTML(g.name)} · ${g.age}岁</h2><p class="meta">${escapeHTML(g.gender)}士 · ${escapeHTML(g.city)}</p><p>${escapeHTML(g.bio)}</p><div class="contact-request"><button class="button primary contact-request-btn" data-guest-id="${g.id}">申请获取联系方式</button><div class="contact-form" hidden><label>你的联系方式（微信/手机号） <input type="text" class="requester-contact" maxlength="60" placeholder="方便站长联系你"></label><label>给对方的留言（选填） <textarea class="requester-message" maxlength="200"></textarea></label><div class="contact-turnstile-slot"></div><button class="button primary submit-contact-request" type="button">提交申请</button><p class="contact-status form-status" role="status"></p></div></div><p><small>联系方式对所有人保密，须经站长与对方本人确认同意后才会转达。请勿向陌生人转账或泄露敏感信息。</small></p></div>`;dialog.showModal()};
document.querySelector('.close').onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog)dialog.close()};
dialog.addEventListener('click',async e=>{
  const openBtn=e.target.closest('.contact-request-btn');
  if(openBtn){const wrap=openBtn.closest('.contact-request');const formEl=wrap.querySelector('.contact-form');formEl.hidden=false;openBtn.hidden=true;const slot=wrap.querySelector('.contact-turnstile-slot');if(window.PEIBANJI_TURNSTILE_SITEKEY&&window.turnstile&&slot&&!slot.dataset.rendered){slot.dataset.widgetId=window.turnstile.render(slot,{sitekey:window.PEIBANJI_TURNSTILE_SITEKEY});slot.dataset.rendered='1'}return}
  const submitBtn=e.target.closest('.submit-contact-request');
  if(submitBtn){const wrap=submitBtn.closest('.contact-request');const guestId=wrap.querySelector('.contact-request-btn').dataset.guestId;const contactInput=wrap.querySelector('.requester-contact');const messageInput=wrap.querySelector('.requester-message');const statusEl=wrap.querySelector('.contact-status');const slot=wrap.querySelector('.contact-turnstile-slot');if(!contactInput.value.trim()){statusEl.textContent='请填写你的联系方式。';return}let token='';if(window.PEIBANJI_TURNSTILE_SITEKEY){token=window.turnstile?.getResponse(slot?.dataset.widgetId)||'';if(!token){statusEl.textContent='请先完成安全验证。';return}}statusEl.textContent='正在提交…';const data=new FormData();data.set('guest_id',guestId);data.set('requester_contact',contactInput.value.trim());data.set('message',messageInput.value.trim());data.set('turnstileToken',token);try{const r=await fetch('/api/contact-requests',{method:'POST',body:data});const result=await r.json();if(!r.ok)throw new Error(result.error||'提交失败。');statusEl.textContent='申请已提交，站长会与对方确认后转达。';submitBtn.disabled=true}catch(err){statusEl.textContent=err.message}}
});
const form=document.querySelector('#registration-form'),bio=form.bio,status=document.querySelector('#form-status');bio.oninput=()=>document.querySelector('#count').textContent=bio.value.length;
async function compressImage(file,maxDim=1600,quality=0.82){if(!file||!file.type.startsWith('image/'))return file;const img=await new Promise((resolve,reject)=>{const image=new Image();const url=URL.createObjectURL(file);image.onload=()=>{URL.revokeObjectURL(url);resolve(image)};image.onerror=reject;image.src=url});let width=img.naturalWidth,height=img.naturalHeight;if(Math.max(width,height)>maxDim){const scale=maxDim/Math.max(width,height);width=Math.round(width*scale);height=Math.round(height*scale)}const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;canvas.getContext('2d').drawImage(img,0,0,width,height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',quality));return blob||file}
form.onsubmit=async e=>{e.preventDefault();if(!form.checkValidity()){status.textContent='请完整填写必填项目并确认隐私说明。';form.reportValidity();return}const file=form.photo.files[0];let photoBlob=null;if(file){if(!file.type.startsWith('image/')){status.textContent='请上传图片格式的照片。';return}status.textContent='正在处理照片…';try{photoBlob=await compressImage(file)}catch{photoBlob=file}}const key=window.PEIBANJI_TURNSTILE_SITEKEY;if(!key){status.textContent='在线提交功能尚未配置完成，请稍后再试或联系站长。';return}const token=window.turnstile?.getResponse();if(!token){status.textContent='请先完成安全验证。';return}status.textContent='正在提交…';const data=new FormData(form);if(photoBlob)data.set('photo',photoBlob,'photo.jpg');data.append('turnstileToken',token);try{const r=await fetch('/api/registrations',{method:'POST',body:data});const result=await r.json();if(!r.ok)throw new Error(result.error||'提交失败。');form.reset();document.querySelector('#count').textContent='0';window.turnstile.reset();status.textContent='资料已提交，站长审核通过后才会公开展示。'}catch(err){status.textContent=err.message}};
async function connectApi(){try{const r=await fetch('/api/guests');if(!r.ok)return;const remote=await r.json();if(Array.isArray(remote)){guests=remote;render()}}catch{/* 未配置 Functions 时保留本地演示 */}}
if(window.PEIBANJI_TURNSTILE_SITEKEY){const script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.async=true;script.onload=()=>window.turnstile.render('#turnstile-slot',{sitekey:window.PEIBANJI_TURNSTILE_SITEKEY});document.head.append(script)}
document.querySelector('#year').textContent=new Date().getFullYear();render();connectApi();
